
TRAIN:
  TYPE: "train_parameters"
  PROJECT_NAME: 'syn2sp_DGTST_XYZ_CAL_M34_LsG'
  
  # for transfer learning
  MAX_ITERS: 100000
  MAX_EPOCHS: 100000

  PREHEAT_STEPS: 5000
  T_VAL_ITER: 1000
  S_VAL_ITER: 4000
  SAVE_MORE_ITER: False
  SAVE_ITER: 80000
  LOG_PERIOD: 50
  PRETRAINPATH: 'path to the preTraModel' # e.g., preTraModel/syn2sp/SourceOnly/checkpoint_epoch_10.tar
  RESUMEPATH: None
  
  EXP_NAME: "LaserMix_Ch10_CE_100Mt9e2_M34_Ps9_Adam25e4" 
  STAGE: "stage_2_SACLM"
  GPU_ID: 5
  DEBUG: False 

SRC_LOSS:
  lambda_lov: 0. 

TGT_LOSS:
  lambda_sac: 0. 
  
  CAL_out: False 

PSEUDO_LABEL:
  use_confidence: True 
  threshold: 0.9

MEAN_TEACHER:
  # 如果使用了teacher模型，那么就是meanteacher模式
  # 如果没有，那就是每个round的初始模型
  TYPE: 'meanTeacher'
  use_mt: True # Mt9e3
  alpha_ema: 0.99
  update_every: 100

  round_period: 20000

HYPERPARAMETER:
  VOXEL_SIZE: 0.05

#------ Network ------
MODEL_G:
  TYPE: "G"
  MODEL_NAME: "MinkUNet34"
  IN_CHANNELS: 3  # coords (xyz) and intensity
  NUM_CLASSES: 14  # Number of valid classes

  # 这个应该放到 dataset_source, 但是为了方便写代码 放到了这里
  aug_shift_prob: -1.
  aug_shift_range: 0.1
  aug_data_prob: 0.

OPTIMIZER:
  TYPE: "Adam"
  LEARNING_RATE_G: 2.5e-4  # max learning rate of G

#------ dataset ------
DATASET_SOURCE:
  TYPE: "SynLiDAR"
  USE_INTENSITY: False # 输入是否使用Intensity
  VOXEL_SIZE: 0.05
  IN_NUM_VOXELS: -80000 
  DATASET_DIR: '~/dataset/SynLiDAR/sub_dataset'

  use_aug_for_laserMix: False
  USE_DGT: False  

DATASET_TARGET:
  TYPE: "SemanticPOSS"
  USE_INTENSITY: False
  VOXEL_SIZE: 0.05
  IN_NUM_VOXELS: -80000
  DATASET_DIR: '~/dataset/semanticPOSS/dataset/sequences/'
  
  use_aug_for_laserMix: False

DATALOADER:
  NUM_WORKERS: 2
  TRA_BATCH_SIZE: 2
  VAL_BATCH_SIZE: 2

DEBUG:
  T_VAL_ITER: 5
  S_VAL_ITER: 20
  LOG_PERIOD: 1
  PREHEAT_STEPS: 10
  EXP_NAME: 'debug'
  PROTO_UPDATE_PERIOD: 15
  T_THRE_ZERO_ITER: 13
  AUX_LOSS_START_ITER: 12

